# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourclass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AlterField(
            model_name='member',
            name='user_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
