# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourclass', '0002_auto_20180320_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='hobbys',
            field=models.ManyToManyField(to='ourclass.Hobby'),
        ),
    ]
